### ISSUE TITLE
AppController

### ISSUE THREAD

**Issue by LorenzoBettini** [LorenzoBettini/attsw-exercise#10]
In the module example-app, implement this class that, by delegating to an **IEmployeeController** (if not already available in the example-core project, then you must create it in that project in the subpackage "controller", with appropriate methods as you see fit) implements this method

```
void performAction(String actionCode, String arg, PrintStream out)
```

if the actionCode is "showAll" then it must print on the passed out the string representing all the employees. If it is "showOne" then it must print on the passed out the string representing the employee with the id specified in the arg parameter. If there is no employee or the requested employee can't be found it should print an appropriate message, relying on the fact that in such situations the corresponding method of IEmployeeController would return **null**. If the actionCode is another string, or if an argument for the action code is expected but not specified, then the method must throw an IllegalArgumentException.

All the behavior must be tested with mocking.

**Comment by Wabri** [comment]
need #18 merged to continue

**Comment by LorenzoBettini** [comment]
@Wabri merging #18 done, please go on (after updating to master)

**Comment by Wabri** [comment]
> If it is "showOne" then it must print on the passed out the string representing the employee with the id specified in the arg parameter

a string rapresenting the employee meens the string get by a toString method of Employee? In that case we should change the implementation of EmployeeController from 
`public String getEmployeeById(String id) { return employeeService.getEmployeeById(id).getName(); }`  
to this one:
 `public String getEmployeeById(String id) { return employeeService.getEmployeeById(id).toString();	}`

**Comment by LorenzoBettini** [comment]
Indeed that implementation was wrong, I didn't notice that. The issue on Controller explicitly said that

```
the returned String must be a suitable representation of employees and a single employee; for the single employee we can rely on its toString() method, which must be implemented if not already available. For the string for the list of employee, each employee representation must be on a different line.
```

thus getName was completely wrong
