### ISSUE TITLE
Setup Coveralls report

### ISSUE THREAD

**Issue by LorenzoBettini** [LorenzoBettini/attsw-exercise#5]
Coveralls is already configured to use this repository.
The Travis file should be updated so that it sends report to Coveralls.
ATTENTION: this task depends on #4 and #2 so you must wait for those two issues to be closed, or at least, use the corresponding issue branches to cherry pick commits.

**Comment by LorenzoBettini** [comment]
@FrancescoTerrosi please go on working on this issue now that the blocking issues have been solved.

**Comment by FrancescoTerrosi** [comment]
I'm sorry for my inactivity in these days but I could not work with my pc. I will try to fix this issue tomorrow.
